//
//  CATSearch.h
//  Cataracte
//
//  Created by Adrien Long on 09/04/2015.
//  Copyright (c) 2015 Adrien Long. All rights reserved.
//

#import "FCModel.h"

@interface CATSearch : FCModel

/// ID Auto-generated by FCModel when inserted in DB.
@property(nonatomic) int64_t id;
/// The phrase to search.
@property (nonatomic, copy) NSString *query;
/// To get a valid list of categories go to https://getstrike.net/api/
@property (nonatomic, copy) NSString *category;
/// To get a valid list of sub-categories go to https://getstrike.net/api/
@property (nonatomic, copy) NSString *subCategory;
/// Time of insertion in database. Must be set manually.
@property (nonatomic) NSDate *createdTime;

@end
